baseURL = 'https://blog.mathis-burger.de'
languageCode = 'en-us'
title = 'Mathis Dev Blog'
theme = "hugo-ficurinia"

copyright = "Mathis Burger"
pagination.pagerSize = 5
summaryLength = 70


[params]
    author = "Mathis Burger"
    description = "My personal blog"

    posts = "posts"
    showPostsLink = true
    extraContentDirs = []
    showcaseDir = "showcase"
    showSinglePageAsHome = false
    homeSinglePage = "/home"

    logo = "/logo.jpg"
    favicon = "/logo.jpg"  # 32x32
    faviconIco = "/logo.jpg"  # 32x32
    appletouch = "/logo.jpg" # 180x180
    svgicon = "/logo.jpg"
    icon512 = "/logo.jpg"  # 512x512 png image

    logoRightOfTitle = false 

    showTags = true
    showRss = true

    imageInArticlePreview = false
    fitImageInArticlePreview = true
    articleSummary = true
    
    fontFamily = "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"
    monospaceFontFamily = "JetBrains Mono"

    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px" 

    paperCards = false
    buttonTags = true
    tagsInArticlePreview = true
    gridView = false
    bigArticleTitle = true
    navtype = "standard"
    enableShadow = false
    menuStyle = "standard" 
    inputStyle = "standard"

    enableSearch = true
    searchbarEverywhere = true
    searchMenuLink = true
    mobileHamburgerNav = true

    enableFeatured = false  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)
    underlineTitleLinks = false

    # enable comments support with cactus comments (cactus.chat)
    #cactusCommentsSiteName = "example.com"
    #cactusCommentsServerName = "cactus.chat"
    #cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"

    # enable analytics using Plausible
    plausibleScriptUrl = "https://analytics.mathis-burger.de/js/script.js"
    plausibleDomain = "blog.mathis-burger.de"

    enableShareOnFediverse = false
    tocBeforeImage = false 
    enableSidebarLayout = false
    forceRedirect = false

    infiniteScrolling = false
    enableFooterColumns = false
    enableJumbotron = false
    enableRelatedArticles = true
    relatedArticlesNum = 2
    randomRelated = true

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/MathisBurger"
        weight = 10
    [[menu.icons]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://x.com/MathisBurger4"
        weight = 20
    [[menu.icons]]
        identifier = "linkedIn"
        name = "LinkedIn"
        url = "https://linkedin.com/in/mathis-burger-93614222b"
        weight = 30
