baseURL = 'https://blog.mathis-burger.de'
languageCode = 'en-us'
title = 'Mathis Dev Blog'
theme = "hugo-ficurinia"

copyright = "Mathis Burger"
pagination.pagerSize = 5
summaryLength = 70


[params]
    author = "Mathis Burger"
    description = "A description for my website"

    posts = "posts"
    showPostsLink = true
    extraContentDirs = []
    showcaseDir = "showcase"
    showSinglePageAsHome = false
    homeSinglePage = "/home"

    # It's best to put these icons in the "static" folder of your site
    logo = "/logo.svg"
    favicon = "/favicon.png"  # 32x32
    faviconIco = "/favicon.ico"  # 32x32
    appletouch = "/apple-touch-icon.png"  # 180x180
    svgicon = "/logo.svg"
    icon512 = "/icon512.png"  # 512x512 png image

    logoRightOfTitle = false  # positions the logo to the right of the title; default: false

    showTags = true  # show the Tags menu item; default true
    showRss = true  # show the link for the RSS feed; default true

    imageInArticlePreview = false  # show images in article preview; default false
    fitImageInArticlePreview = false  # make article preview images fit the article preview instead of getting cropped
    articleSummary = true  # show a summary in article preview; default true
    
    fontFamily = "JetBrains Mono"  # changes the font, default "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"  # font used for titles and headings
    monospaceFontFamily = "JetBrains Mono"  # changes the monospace font for code, default "JetBrains Mono"

    # multipliers applied to font sizes, useful for custom fonts that may be too big or too small
    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px"  # maximum width of the site content, css syntax

    paperCards = false  # enable paper card style; default false
    buttonTags = false  # enable button tag style; default false
    tagsInArticlePreview = true  # enable tags list in the article preview card
    gridView = false  # show post list as a grid. goes well with paperCards
    bigArticleTitle = false  # makes the title in the single article view bigger
    navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
    enableShadow = false  # shows a shadow around some elements
    menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"
    inputStyle = "standard" # changes the style of inputs (like the searchbar), available styles are: "standard", "buttons"

    enableSearch = true  # enable search page
    searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
    searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
    mobileHamburgerNav = false  # alternative hamburger menu layout for the main nav menu when screen is small

    enableFeatured = false  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)
    underlineTitleLinks = false

    # enable comments support with cactus comments (cactus.chat)
    #cactusCommentsSiteName = "example.com"
    #cactusCommentsServerName = "cactus.chat"
    #cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"

    # enable analytics using Plausible
    plausibleScriptUrl = "https://something.com/..."
    plausibleDomain = "example.com"

    enableShareOnFediverse = false  # enable a button at the end of an article to share it on the fediverse
    tocBeforeImage = false  # show the table of contents before the main article image; default false
    enableSidebarLayout = false
    forceRedirect = false

    infiniteScrolling = false
    enableFooterColumns = false
    enableJumbotron = false
    enableRelatedArticles = true
    relatedArticlesNum = 2
    randomRelated = true

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/MathisBurger"
        weight = 10
    [[menu.icons]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://x.com/MathisBurger4"
        weight = 20
    [[menu.icons]]
        identifier = "linkedIn"
        name = "LinkedIn"
        url = "https://linkedin.com/in/mathis-burger-93614222b"
        weight = 30
